server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      
      routes:
        # ROUTE AUTH
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/auth
        
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/users
        
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookingService
                fallbackUri: forward:/fallback/bookings
        
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
          filters:
            - name: CircuitBreaker
              args:
                name: eventService
                fallbackUri: forward:/fallback/events

# Configuration EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

resilience4j:
  circuitbreaker:
    instances:
      eventService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      bookingService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      userService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

# Actuator endpoints - CORRIGEZ CECI
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus  # ← AJOUTEZ "gateway"
  endpoint:
    gateway:
      enabled: true  # ← AJOUTEZ CETTE LIGNE
    health:
      show-details: always
    routes:
      enabled: true  # ← OPTIONNEL: pour voir les routes

# Logging
logging:
  level:
    com.eventplatform: DEBUG
    org.springframework.cloud: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.gateway: DEBUG