server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      
      routes:
        - id: user-service
          uri: http://localhost:8083  # ← User Service port 8083
          predicates:
            - Path=/api/users/**      # ← UserController a @RequestMapping("/api/users")
          filters:
            # PAS de RewritePath !
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/users
        
        - id: booking-service
          uri: http://localhost:8082  # ← Booking Service port 8082
          predicates:
            - Path=/api/bookings/**   # ← BookingController a @RequestMapping("/api/bookings")
          filters:
            - name: CircuitBreaker
              args:
                name: bookingService
                fallbackUri: forward:/fallback/bookings

# Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      eventService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      bookingService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      userService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s