server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
        pool:
          max-idle-time: 60s
      
      routes:
        # ROUTE SIMPLE SANS FILTERS COMPLEXES
        - id: user-service-all
          uri: lb://USER-SERVICE  # ou http://localhost:8083
          predicates:
            - Path=/api/auth/**, /api/users/**
          # PAS de filters pour l'instant
        - id: checkin-service
          uri: lb://CHECKIN-SERVICE
          predicates:
            - Path=/api/qr-codes/**, /api/checkin/**

        - id: refund-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/refunds/**
        # Route EVENT-SERVICE
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events/**
        
        # Route BOOKING-SERVICE
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG