server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      
      routes:
        # ROUTE AUTH - AVEC RETRY au lieu de CircuitBreaker pour POST
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
          filters:
            # Utilisez Retry pour les POST (préserve la méthode)
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
                methods: POST,GET
                series: SERVER_ERROR
            # Fallback configuré
            - name: FallbackHeaders
              args:
                executionExceptionTypeHeaderName: Test-Header
            # CircuitBreaker seulement pour monitor, pas pour modifier
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/auth
                statusCodes: "500,502,503,504"
        
        # Route pour les autres endpoints auth
        - id: auth-other
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
            - Method=GET,OPTIONS,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/auth
        
        # ROUTE USER-SERVICE
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/users
        
        # ROUTE EVENT-SERVICE
        - id: event-service
          uri: lb://event-service  # Utilisation de service discovery
          predicates:
            - Path=/api/events/**
          filters:
            - name: CircuitBreaker
              args:
                name: eventService
                fallbackUri: forward:/fallback/events
        
        # ROUTE BOOKING-SERVICE
        - id: booking-service
          uri: lb://booking-service  # Utilisation de service discovery
          predicates:
            - Path=/api/bookings/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookingService
                fallbackUri: forward:/fallback/bookings

# Service Discovery REQUIS pour l'exigence #3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${server.port}

# Circuit Breaker REQUIS pour l'exigence #2
resilience4j:
  circuitbreaker:
    instances:
      userService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      userServiceRegister:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
      eventService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      bookingService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

# Actuator pour monitoring REQUIS
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus,circuitbreakers
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
    circuitbreakers:
      enabled: true

# Logging pour debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG