server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # ← CHANGER À true POUR SERVICE DISCOVERY
          lower-case-service-id: true
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      
      routes:
        # Route pour la page d'accueil de l'API Gateway
        - id: gateway-home
          uri: http://localhost:8080
          predicates:
            - Path=/
          filters:
            - SetResponseHeader=Content-Type,application/json
            - SetResponseBody={"service": "API Gateway", "status": "UP", "message": "Event Platform Microservices", "timestamp": "{{#now}}"}
        
        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/users
            - RewritePath=/api/(?<segment>.*), /$\{segment}  # ← ENLEVER /api PREFIX
        
        # Booking Service
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookingService
                fallbackUri: forward:/fallback/bookings
            - RewritePath=/api/(?<segment>.*), /$\{segment}  # ← ENLEVER /api PREFIX
        
        # Event Service
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
          filters:
            - name: CircuitBreaker
              args:
                name: eventService
                fallbackUri: forward:/fallback/events
            - RewritePath=/api/(?<segment>.*), /$\{segment}  # ← ENLEVER /api PREFIX
        
        # Fallback routes
        - id: fallback-routes
          uri: http://localhost:8080
          predicates:
            - Path=/fallback/**

# Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      eventService:
        base-config: default
      bookingService:
        base-config: default
      userService:
        base-config: default

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG