server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
            allowed-headers: "*"
            allow-credentials: true
      
      routes:
        # ROUTE AUTH SANS CIRCUIT BREAKER TEMPORAIREMENT
        - id: auth-no-cb
          uri: http://localhost:8083
          predicates:
            - Path=/no-cb/api/auth/**
          filters:
            - RewritePath=/no-cb/api/auth/(?<segment>.*), /api/auth/$\{segment}
        
        # ROUTE AUTH avec Circuit Breaker modifié
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
          filters:
            # Circuit Breaker avec configuration spécifique
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/auth
                statusCodes: "5xx"
        
        # ROUTE SPÉCIFIQUE pour register (POST seulement)
        - id: auth-register-post
          uri: http://localhost:8083
          predicates:
            - Path=/post/api/auth/register
            - Method=POST
          filters:
            - RewritePath=/post/api/auth/register, /api/auth/register
        
        # ROUTE USER-SERVICE
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**
        
        # ROUTE EVENT-SERVICE
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
        
        # ROUTE BOOKING-SERVICE
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**

# Circuit Breaker config
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
    instances:
      userService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG