server:
  port: 8082

spring:
  application:
    name: booking-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/booking_db
    username: postgres
    password: jihane123
    driver-class-name: org.postgresql.Driver
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    enabled: false

  jpa:  # ← AJOUTER CETTE SECTION
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Resilience4j pour Feign Client
resilience4j:
  circuitbreaker:
    instances:
      eventService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# ET ajoutez pour désactiver RabbitMQ health check :
management:
  health:
    rabbit:
      enabled: false