server:
  port: 8082

spring:
  application:
    name: booking-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/booking_db
    username: postgres
    password: jihane123
    driver-class-name: org.postgresql.Driver
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Resilience4j pour Feign Client
resilience4j:
  circuitbreaker:
    instances:
      eventService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000