server:
  port: 8081

spring:
  application:
    name: event-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/event_db
    username: postgres
    password: jihane123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000