server:
  port: 8081

spring:
  application:
    name: event-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/event_db
    username: postgres
    password: jihane123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  health:
    rabbit:
      enabled: false