server:
  port: 8083

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: jihane123
    driver-class-name: org.postgresql.Driver
  eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true  # ← AJOUTEZ
    
  instance:
    prefer-ip-address: true