server:
  port: 8083

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: jihane123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Ajouter cette section
app:
  frontend:
    url: http://localhost:3000