server:
  port: 8083

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: jihane123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_SMTP_AUTH:true}
          starttls:
            enable: true  # ⬅️ 'enable' pas 'enabled'
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

app:
  frontend:
    url: http://localhost:3000